import React from "react";

const ChapterNine = () => {
  return (
    <div id="multinational" className="space-y-8 scroll-mt-28 border-t border-slate-100 pt-8">
      {/* Chapter Title & Main Summary */}
      <div className="space-y-2">
        <span className="text-Primary font-medium text-sm md:text-base">
          Chapter 9
        </span>
        <h2 className="text-3xl md:text-4xl font-bold text-slate-800">
          Gambling operators as multinational corporations
        </h2>
        <p className="text-slate-500 text-sm md:text-base leading-relaxed max-w-4xl">
          The UK gambling market is dominated by a small number of multinational holding companies, listed on the FTSE and operating across multiple jurisdictions. Their political-influence apparatus, lobbying capacity and regulatory-arbitrage options are structurally different from a domestic retail business.
        </p>
      </div>

      {/* Sub-block: The shape of the market */}
      <div className="space-y-3">
        <h3 className="text-lg font-bold text-slate-800">
          The shape of the market
        </h3>
        <ul className="space-y-3 text-sm md:text-base text-slate-600 pl-4 list-disc marker:text-slate-300">
          <li className="leading-relaxed">
            UK gross gambling yield (GGY) was approximately <span className="font-bold text-slate-800">£15 Billion Per Year In 2024</span>, roughly <span className="font-bold text-slate-800">£280 Per UK Adult</span>. Online slots and remote sports betting are the largest categories.
          </li>
          <li className="leading-relaxed">
          Industry margin concentrates heavily on a small minority of customers. NatCen's Patterns of Play (2023) found the top 10% of online customers generate around 79% of net revenue, with the top 1% alone generating roughly 37%. The "heavy-tail" customer is almost always a customer in harm: the WHO synthesis estimates around 60% of gambling losses are generated by people gambling at harmful levels.
          </li>
        </ul>
      </div>

      {/* Sub-block: Why this shape matters */}
      <div className="space-y-3">
        <h3 className="text-lg font-bold text-slate-800">
          Why this shape matters
        </h3>
        <ul className="space-y-4 text-sm md:text-base text-slate-600 pl-4 list-disc marker:text-slate-300">
          <li className="leading-relaxed">
            <span className="font-bold text-slate-800">Lobbying capacity.</span> Multinational operators fund cross-party lobbying, contract communications agencies, and run sustained press operations. The Gambling Commission's own capacity is repeatedly outweighed by the regulatory resources of those it regulates.
          </li>
          <li className="leading-relaxed">
            <span className="font-bold text-slate-800">Regulatory arbitrage.</span> Operators can shift product mix, marketing intensity or in some cases jurisdictional footprint in response to regulation. Policy design needs to account for this.
          </li>
          <li className="leading-relaxed">
            <span className="font-bold text-slate-800">Revolving door.</span> A steady traffic of senior personnel between operators, trade bodies, regulators and ministerial offices is documented. We support a statutory cooling-off period{" "}
            <a
              href="#"
              className="text-Primary font-medium underline hover:text-opacity-80 transition-colors"
            >
              (see our policy positions)
            </a>
            .
          </li>
        </ul>
      </div>
    </div>
  );
};

export default ChapterNine;