import React from "react";
import { Link } from "react-router-dom";

const ChapterNine = () => {
  return (
    <div
      id="multinational"
      className="space-y-8 scroll-mt-28 border-t border-gray-100 pt-8"
    >
      {/* Chapter Label & Main Heading */}
      <div className="space-y-2">
        <span className="text-xs font-bold text-[#0093D0] uppercase tracking-widest block">
          CHAPTER 9
        </span>
        <h2 className="text-3xl md:text-5xl font-bold text-gray-900 tracking-tight">
          Gambling operators as multinational corporations
        </h2>
        <p className="text-gray-700 text-base md:text-lg leading-relaxed pt-2">
          The UK gambling market is dominated by a small number of multinational holding
          companies, listed on the FTSE and operating across multiple jurisdictions. Their
          political-influence apparatus, lobbying capacity and regulatory-arbitrage options are
          structurally different from a domestic retail business.
        </p>
      </div>

      {/* Sub-block: The shape of the market */}
      <div className="space-y-3">
        <h3 className="text-xl md:text-2xl font-bold text-gray-900">
          The shape of the market
        </h3>
        <ul className="space-y-3 text-sm md:text-base text-gray-700 pl-5 list-disc marker:text-gray-400">
          <li className="leading-relaxed">
            UK gross gambling yield (GGY) was approximately{" "}
            <strong className="font-bold text-gray-900">£15 billion per year</strong> in 2024,
            roughly <strong className="font-bold text-gray-900">£280 per UK adult</strong>.
            Online slots and remote sports betting are the largest categories.
          </li>
          <li className="leading-relaxed">
            The largest UK-facing operators (Flutter, Entain, bet365, Sky Betting &amp; Gaming,
            William Hill, Betfred) account for the bulk of the market.
          </li>
          <li className="leading-relaxed">
            Industry margin concentrates heavily on a small minority of customers. NatCen's{" "}
            <em className="italic">Patterns of Play</em> (2023) found the{" "}
            <strong className="font-bold text-gray-900">
              top 10% of online customers generate around 79% of net revenue
            </strong>
            , with the top 1% alone generating roughly 37%. The "heavy-tail" customer is almost
            always a customer in harm: the WHO synthesis estimates around 60% of gambling losses
            are generated by people gambling at harmful levels.
          </li>
        </ul>
      </div>

      {/* Sub-block: Why this shape matters */}
      <div className="space-y-3">
        <h3 className="text-xl md:text-2xl font-bold text-gray-900">
          Why this shape matters
        </h3>
        <ul className="space-y-3 text-sm md:text-base text-gray-700 pl-5 list-disc marker:text-gray-400">
          <li className="leading-relaxed">
            <strong className="font-bold text-gray-900">Lobbying capacity.</strong> Multinational
            operators fund cross-party lobbying, contract communications agencies, and run
            sustained press operations. The Gambling Commission's own capacity is repeatedly
            outweighed by the regulatory resources of those it regulates.
          </li>
          <li className="leading-relaxed">
            <strong className="font-bold text-gray-900">Regulatory arbitrage.</strong> Operators
            can shift product mix, marketing intensity or in some cases jurisdictional footprint
            in response to regulation. Policy design needs to account for this.
          </li>
          <li className="leading-relaxed">
            <strong className="font-bold text-gray-900">Revolving door.</strong> A steady traffic
            of senior personnel between operators, trade bodies, regulators and ministerial
            offices is documented. We support a statutory cooling-off period (see our{" "}
            <Link
              to="/policy-and-advocacy"
              className="text-gray-900 font-medium underline hover:text-[#0093D0] transition-colors"
            >
              policy positions
            </Link>
            ).
          </li>
        </ul>
      </div>
    </div>
  );
};

export default ChapterNine;